# Generated by Django 3.0.5 on 2020-05-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasque_rest', '0002_auto_20200525_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasque_rest.Task'),
        ),
        migrations.AlterField(
            model_name='hyperlinkresource',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasque_rest.Task'),
        ),
    ]
