# Generated by Django 3.0.5 on 2020-05-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasque_rest', '0004_auto_20200525_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasque_rest.Task'),
        ),
        migrations.AlterField(
            model_name='hyperlinkresource',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasque_rest.Task'),
        ),
    ]
