# Generated by Django 3.0.5 on 2020-05-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasque_rest', '0005_auto_20200527_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
